server:
  port: 8090

spring:
  application:
    name: common

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

internal-properties:
  path: "file:///internal.properties"