server:
  port: 8079

spring:
  application:
    name: apigateway

zuul:
  routes:
    common:
      path: /props/**
      url: http://localhost:8090/props
    one:
      path: /triggerMetric/**
      url: http://localhost:8086/triggerMetric
    two:
      path: /triggerController2Metric/**
      url: http://localhost:8085/triggerController2Metric


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
