server:
  port: 8085

spring:
  application:
    name: two

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

logging:
  level:
    com:
      netflix:
        servo: DEBUG